[database]
path = "data/catalog.db"

[library]
main = "/tmp/games"
#test = "/tmp/test"

[dropzone]
path = "/tmp/downloads"

[server]
listen = "0.0.0.0"
port = 8000
api_key = "secret"

[logging]
level = "DEBUG"
console = true 
file = "backend.log"
file_max_bytes = 10485760
file_backup_count = 5
buffer_capacity = 1000